__include__:
- deimv2_hgnetv2_atto_coco.yml
batch_size: 16
checkpoint_freq: 5
clip_max_norm: 1.0
ema:
  decay: 0.9999
  type: ModelEMA
  warmups: 400
epoches: 50
eval_spatial_size:
- 640
- 640
flat_epoch: 29
lrsheduler: flatcosine
no_aug_epoch: 0
num_classes: 5
optimizer:
  betas:
  - 0.9
  - 0.999
  type: AdamW
  weight_decay: 0.0001
print_freq: 50
remap_mscoco_category: true
save_ema: false
save_optimizer: false
train_dataloader:
  dataset:
    ann_file: app_data/work_dir/sly_project/train/annotations/coco_instances.json
    img_folder: app_data/work_dir/sly_project/train/img
  num_workers: 8
  total_batch_size: 16
use_amp: true
use_ema: false
val_dataloader:
  dataset:
    ann_file: app_data/work_dir/sly_project/val/annotations/coco_instances.json
    img_folder: app_data/work_dir/sly_project/val/img
  num_workers: 8
  total_batch_size: 32
warmup_iter: 200
